version: '2'
services:
  data-uploader:
    image: postgres:10.1
    volumes:
      - ./create_schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example
    ports:
      - 5432:5432
